CREATE USER footmgr IDENTIFIED WITH mysql_native_password BY 'France@00';

GRANT ALL PRIVILEGES ON league.* to 'footmgr';

CREATE TABLE TEAM (
    TEAMID INT AUTO_INCREMENT,
    TEAMNAME VARCHAR(70) NOT NULL UNIQUE,
    TRAINERNAME VARCHAR(70) NOT NULL UNIQUE,

    CONSTRAINT PK_TEAM PRIMARY KEY (TEAMID)
);
CREATE TABLE PLAYER (
    NAME VARCHAR(70) NOT NULL,
    PNUMBER INT NOT NULL, 
    TEAMNAME VARCHAR(70) NOT NULL,
    CONSTRAINT PK_PLAYER PRIMARY KEY (TEAMNAME, PNUMBER),
    CONSTRAINT FK_TEAMNAME_TEAM FOREIGN KEY (TEAMNAME) REFERENCES TEAM(TEAMNAME)
);
CREATE TABLE MATCHINFO (
    TEAMA VARCHAR(70) NOT NULL,
    TEAMB VARCHAR(70) NOT NULL, 
    MATCHTIME DATETIME NOT NULL,
    CONSTRAINT PK_MATCHINFO PRIMARY KEY(TEAMA, TEAMB, MATCHTIME),
    CONSTRAINT FK_TEAMA_TEAM FOREIGN KEY (TEAMA) REFERENCES TEAM(TEAMNAME),
    CONSTRAINT FK_TEAMB_TEAM FOREIGN KEY (TEAMB) REFERENCES TEAM(TEAMNAME),
);
CREATE TABLE USERS (
    USERID INT AUTO_INCREMENT NOT NULL,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLES INT DEFAULT 0,
    CONSTRAINT PK_USERID PRIMARY KEY (USERID)
);

ALTER TABLE TEAM ADD USER VARCHAR(255);
ALTER TABLE TEAM ADD CONSTRAINT FK_TEAM_USER FOREIGN KEY (USER) REFERENCES USERS (USERNAME);

/**
11 : admin
01 : guest
10 : user
**/
INSERT INTO USERS (USERNAME, PASSWORD, ROLES) VALUES
    ('admin', md5('admin'), 11),
    ('user', 'ee11cbb19052e40b07aac0ca060c23ee', 10);


SELECT TEAM.TEAMNAME as teamName, TEAM.TRAINER as trainerName, PLAYER.NAME as playerName, PLAYER.PNUMBER as playerNumber FROM PLAYER
                JOIN TEAM
                ON PLAYER.TEAMID = TEAM.TEAMID &&  (TEAM.EMAIL = 'cinah33412@mrisemail.com' || null = 11);

